### ISSUE TITLE
Design and Build KPT: About Page

### ISSUE THREAD

**Issue by bnaolu** [Bixal/rapid-response-team#25]
- [x] Design in [Figma](https://www.figma.com/file/s0zKIEPUh1k0oW4FDvVeIb/USWDS-Templates-(Truss-Lib-v2.10.0)?node-id=5%3A0)
- [x] Build in [Codepen](https://codepen.io/bnaolu/pen/YzNoqJw)
- [x] Review

**Comment by pglevy** [comment]
Overall, looks really good! Nice use of sections and grids. I think we should try to move headers and footers to includes instead of repeating every time (though it could cause some content issues). I've created and assigned issues for those to me. A few changes and questions below. Mentioning @kbchumley for visibility on some of the issues covered.

Questions:

1. What's the purpose of the CSS you added?

Content:

1. add link text for "simple link"
1. add images for "highlights"
1. revisit overall heading structure of doc:
  - page title should be h1
  - major sections should be h2
  - headings within h2s should be h3, etc.


Code:

1. avoid extra spaces in between HTML tags (ex: line 19, though we'll break header out into an include)
1. let's avoid inline css styling (line 54, also 112 and others; use height and width utility classes instead)
1. let's avoid usa-prose (line 67; instead, link to "external" CSS for default Public Sans settings, like [this example](https://codepen.io/pglevy/pen/dyNOmym))
1. for links in body text and general content (not nav), add class "usa-link"



![image](https://user-images.githubusercontent.com/5177337/117471996-6bf88800-af26-11eb-8a14-769e910a0868.png)

**Comment by pglevy** [comment]
For Figma, we want the mockup and code to be as similar as possible. So that means things like:

- text styles (like headings that should match the codepen)
- grid settings
- alignment
- content

I would take another pass at the mockup to get it more inline with the codepen.

**Comment by bnaolu** [comment]
| _What's the purpose of the CSS you added?_
- I was having issues getting the background image to align and fit properly, so the current CSS code allows the image to do just that. I'll definitely look into alternatives to try to avoid using CSS! :)

Thank you for reviewing! I'll go back and make the changes you mentioned.

**Comment by pglevy** [comment]
Gotcha. Maybe their [landing page template](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.11.2/components/preview/layout--landing.html) has some inspiration.

**Comment by bnaolu** [comment]
- Under the "Staff Section", I changed the "tablet:grid-col-4" to "mobile-lg:grid-col-4" to see how the images would look at 480px (Figma mobile lg size). Previously, the images were overwhelmingly big on when displayed on mobile, but changing the grid to "mobile-lg" helped to make that a bit nicer. Let me know if you like it or hate it lol
- All of my heading and paragraph tags should be properly aligned between Figma and Codepen. If you catch something off, let me know and I'll make the changes.

**Comment by bnaolu** [comment]
@pglevy @kbchumley 

Fixes from Philip's review:
- Reformatted the comment structure.
- Removed 'hero-image-container', 'hero-image', 'waterboat-image', and 'desktop:height-mobile' classes.
  - These were there from previous versions of me messing around with the background image and css. Thank you for catching that :)
- Added "usa-intro" class to the About section paragraph tag.
- Values section: fixed spacing between heading and paragraph + added proper alt img text.
- Staff section: fixed spacing between title and name (staff section) + removed extra div + <a> has href with js void.

>Where do the "usa-graphic-list" and "usa-media-block" classes come from?

- Here's the [reference](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/release-2.11.2/components/preview/layout--landing.html). Look under the main tag and it should be the third section. 
- Let me know if you would like for me to figure out another way to structure this area; open to any and everything!

**Comment by bnaolu** [comment]
Moving this issue from 'in-review' to 'done'.
Final Hi-Fi frames are marked with the green "Complete" tag.
- [x] Figma restructured to match CodePen
- [x] 1:1 Review with Philip
