### ISSUE TITLE
Design and Build KPT: Address Page

### ISSUE THREAD

**Issue by bnaolu** [Bixal/rapid-response-team#26]
- [x] Design in Figma
- [x] Build in Codepen
- [x] move to GH

**Comment by bnaolu** [comment]
Address page is ready for review in [figma](https://www.figma.com/file/s0zKIEPUh1k0oW4FDvVeIb/USWDS-Templates-(Truss-Lib-v2.10.0)?node-id=5%3A0) at the top of the page! :)
Open to suggestions for adding additional elements!

**Comment by bnaolu** [comment]
Alright team, ready for another round of review in [figma](https://www.figma.com/file/s0zKIEPUh1k0oW4FDvVeIb/USWDS-Templates-(Truss-Lib-v2.10.0)?node-id=5%3A0). Here's how the [codepen](https://codepen.io/bnaolu/pen/XWMRyae?editors=1000) looks like; don't mind the spacing in the code for now, it just helps me determine where things are.

Fixed changes from your feedback on Figma, Philip:
- fixed spacing 
   - most are 24 px, let me know how your thoughts on how this looks/feels.
- elements fitted to grid
- added header and footer components for both mobile and desktop
- fixed alignment with buttons
- added an "Add new" button for additional addresses

**Comment by bnaolu** [comment]
Updated [codepen](https://codepen.io/bnaolu/pen/xxqjKZd?editors=1000).
Let me know what you think.

- took off radius from the input fields
- placed phone number field above the email field
- added 'Update preference' fieldset with a light border

**Comment by pglevy** [comment]
Sorry for the long delay in getting back to this. A few items on the codepen:

1. Since "Address" is the page title in this case, let's mark it up as an h1 (inside the legend element), instead of using the usa-legend--large class.
2. Similar to 1, use h2s for the other sections; use font sizing classes only if need in addition to the heading elements.
3. Instead of radio buttons here (which forces the user to pick a choice and us to pick a default), let's just do the "yes" option as an unchecked checkbox. In that case, we probably don't need the fieldset. Sorry about the back and forth on that. 😬
4. For State, can you use the combobox from the [USWDS example](https://designsystem.digital.gov/templates/form-templates/address-form/)?

**Comment by bnaolu** [comment]
No worries! Thank you for your review, Philip!
- [x] set "address" as h1 element within legend element
- [x] changed "contact details" and "mailing address" subheadings to h2 elements
- [x] removed email notification fieldset and changed to unchecked checkbox.
- [x] used combobox for state dropdown

Alright, let me know if I did the h2 subheadings correctly. Also, I was messing around with formatting this in Figma and it may seem like it doesn't line up to the grid, but I think that's because of the divs with flex classes. Please let me know if I'm doing this correctly or if you know a better way to go about this 😂

**Comment by pglevy** [comment]
The form element has a max-width setting. At 1200px, it's about 400px. So I would set up Figma to use a 4-col width (centered, or offset by 4 cols). 

![image](https://user-images.githubusercontent.com/5177337/121947421-061cce80-cd24-11eb-9ca7-0960e55b76e5.png)

**Comment by pglevy** [comment]
@pglevy to double check in figma, @bnaolu to start moving into GH repo.

**Comment by bnaolu** [comment]
- [x] merged in GH
- [x] changes made in Figma
- [ ] review Figma before closing

**Comment by pglevy** [comment]
reviewed and tweaked figma, mostly spacing and some text styles
