### ISSUE TITLE
Design and Build KPT: Blog List 

### ISSUE THREAD

**Issue by bnaolu** [Bixal/rapid-response-team#31]
- [x] Design in Figma
- [x] Build in Codepen
- [x] Review

**Comment by kbchumley** [comment]
@pglevy @bnaolu Blog page design is ready for review in figma - I made 2 different versions

**Comment by kbchumley** [comment]
ready for review in [codepen ](https://codepen.io/kbchumley/pen/xxqaybo?editors=1000)@bnaolu @pglevy

**Comment by bnaolu** [comment]
Ooo, this looks awesome, Kayla! My only feedback would be to include a source link but that's it! Very nice job 🤗

**Comment by kbchumley** [comment]
just realized i accidently linked the codepen for the text page in the blog page issue... @pglevy @bnaolu the blog page 2nd design revision is ready in figma for feedback

**Comment by pglevy** [comment]
> ready for review in [codepen ](https://codepen.io/kbchumley/pen/xxqaybo?editors=1000)@bnaolu @pglevy

Can you update this link?

**Comment by pglevy** [comment]
Hey Kayla. This is looking good. Some feedback:

1. I think using the sidebar area for Categories instead of Tags is going to be a [conventional](https://wordpress.com/support/posts/categories-vs-tags/), useful example for a template. See this [USDA example](https://www.usda.gov/media/blog/2021/06/10/humble-beginnings-homeownership). Categories are like folders you put a post in. Tags are more specific aspects of the post that connect it to other posts in other categories. As a navigational convention, you can end up with many tags, some of which can be wordy, so it's generally not going to be helpful to display them all together in this way.
2. For the "more" button, let's use sentence case and the word "posts" instead of "articles."
3. Let's start to get some realistic content for the blog posts, so we can see how things are adapting to different screen sizes.
4. Let's link the post titles and images. (They can be dead links, but should be interactive.)
5. See guidance on interactive/static tags. I don't have a preference for what we do in this case, but if we're going to link the tags in the cards, let's wrap the anchor around the span element (instead of the just the text) so the whole thing is interactive.
6. Seems like you may be in progress on something because this was working, but as of now, the sidebar is showing at the bottom, even at large page widths. Should probably keep 2-col layout at larger widths.

**Comment by kbchumley** [comment]
The order of the sidebar vs blog posts work in mobile but do not act right in desktop @pglevy

**Comment by pglevy** [comment]
@kbchumley, what's the content source for this template?

**Comment by pglevy** [comment]
@kbchumley, still work-in-progress, but since I'm moving templates over to GH, I started a [branch for this template here](https://github.com/Bixal/uswds-page-templates/tree/template-blog-list). I tried using side nav component for category list. But you can see the column order is now working as expected. In some ways it's easier to see what's going on in the template without all the repeated content.

One thing that might have been causing issues is the card component was missing the wrapping UL and LI elements. This may be helping the cards "stay together" instead of floating around the page based on their size. Not sure, but if it wasn't the columns, that might have been it.

![image](https://user-images.githubusercontent.com/5177337/122297897-11116380-ceca-11eb-9fb4-704b3145d47b.png)

**Comment by kbchumley** [comment]
> @kbchumley, still work-in-progress, but since I'm moving templates over to GH, I started a [branch for this template here](https://github.com/Bixal/uswds-page-templates/tree/template-blog-list). I tried using side nav component for category list. But you can see the column order is now working as expected. In some ways it's easier to see what's going on in the template without all the repeated content.
> 
> One thing that might have been causing issues is the card component was missing the wrapping UL and LI elements. This may be helping the cards "stay together" instead of floating around the page based on their size. Not sure, but if it wasn't the columns, that might have been it.
> 
> ![image](https://user-images.githubusercontent.com/5177337/122297897-11116380-ceca-11eb-9fb4-704b3145d47b.png)

Okay thanks philip, ill take a look at the li and see if thats my issue

**Comment by kbchumley** [comment]
> @kbchumley, what's the content source for this template?

https://codepen.io/kbchumley/pen/MWpzOxY?editors=1010

**Comment by pglevy** [comment]
> > @kbchumley, what's the content source for this template?
> 
> https://codepen.io/kbchumley/pen/MWpzOxY?editors=1010

I meant the real site that we're pulling content from. See the source links toward the bottom of the other templates.

**Comment by pglevy** [comment]
PR ready for review in repo
