### ISSUE TITLE
KPT: Account Page

### ISSUE THREAD

**Issue by bnaolu** [Bixal/rapid-response-team#39]
- [x] Design in Figma
- [x] Build in CodePen
- [x] move to GH

**Comment by bnaolu** [comment]
Hi team, I apologize for the delayed response to getting this page up and running. 
To preface: I took inspiration from the GHSC medical supply catalog and started creating an account page based on what we knew from there. Let me know if I should include this as a source.

The [codepen](https://codepen.io/bnaolu/pen/zYZVOYY?editors=1000) is ready for review.

**Comment by pglevy** [comment]
Some feedback on the codepen:

1. Let's use "usa-intro" class on second line of hero section.
2. Try removing top-margin of hero section. (It's only at smaller sizes.)
3. Orders and Saved Products should be h2s.
4. The combo of the shadow with the fairly dark border seems a little awkward. Maybe play around with that interaction.
5. What about accent-cool-lighter for hover background color?
6. Since those look like cards, I wonder if we should use the card component markup... but not critical.
7. Carrington is a cool name.
8. Need more realistic phone numbers and zip codes.
9. Email addresses get problematic at smaller col widths because they don't wrap. Play with window size and maybe consider only 6-col for when using email addresses.
10. Avoid partial sentences (when possible) ("Receive updates and news via:"). It's not multi-language friendly.
11. The help and more links feel a little out of place (as a list of text links) with everything else going on. Not sure.
12. Revisit heading names. Using "settings" twice.
13. Not sure you need display-flex on the "cards." They're not going to full-width at small screen, so double check that.
14. HRs are kinda blah. Try adding bottom border to headings instead.

**Comment by bnaolu** [comment]
Thank you, Philip! And the name Carrington is a cool name 😂, it was the first name that popped into my head.
Here are the changes I made to the [codepen](https://codepen.io/bnaolu/pen/zYZVOYY?editors=1000) based on the feedback:
- "usa-intro" used on second line in hero section
- top-margin removed on hero section
   - blending of the menu bottom and hero section occurs at smaller widths; let me know your thoughts on how this feels.
- removed the original "cards" I had and replaced with actual card component
   - added the accent-cool-lighter hover background...thoughts?
   - h2 headings applied
- phone numbers and emails address more realistic
   - 6-col applied to div with email addresses
- restructured 'help and more' section to the bottom of the page
   - removed the list and added 'display-block' class
   - do these changes help bring value to it? If not, we can scrap it
- reworded the partial sentence under 'communication settings'
- removed redundant "settings" in heading names
- took out use of HRs and added bottom borders

**Comment by pglevy** [comment]
Nice work!

Just a couple things:

1. I'm OK with the blending of the Menu button.
2. Try a smidge of bottom padding for the h2s with the borders.
3. One thing I didn't catch: the Help links should be marked up as a [usa-list](https://designsystem.digital.gov/components/list/). The spacing is too tight, but that's built into the list styling.

Once you take care of those, this one is good to go to GH.

**Comment by bnaolu** [comment]
Awesome, thank you for catching that usa-list issue! My head is a mess right now 🙃
Anyways, added padding to the h2s and they look a LOT better. I'll convert this over to the repo now. 
Let me know if you see any other issues or would like any other changes made.

**Comment by pglevy** [comment]
Made some minor tweaks to figma. Closing.
