### ISSUE TITLE
Get feedback on USWDS Page Templates

### ISSUE THREAD

**Issue by pglevy** [Bixal/rapid-response-team#63]

**Comment by bnaolu** [comment]
# Summary notes:
[Transcript - USWDS Summary of Findings.pdf](https://github.com/Bixal/rapid-response-team/files/6909964/Transcript.-.USWDS.Summary.of.Findings.pdf)

## Participant A
- Tools currently using:
   - Adobe XD, Pattern.io, USWDS, etc.

- Initial impressions:
   - Everything was super great to be able to have a jumping point for each project.
   - It's good for rapid prototyping potential solutions for user testing, but would also be good for testing out functionality prototypes for clients.
   - I would definitely be interested in having a conversation with my developer to use these page templates instead of having to build something from scratch.
   - What you have here nails down what I would look for in order to build out a website.
   - I can definitely see people using this a lot, especially since you've made it easy to access (i.e. open in browser, open in Figma). 

- Current Design-Dev collaboration:
   - Tackling from a design system approach:
      - documentation by hand: setting up color tokens, providing labels for line height and font families, etc.

- Hurdles:
   - Can't utilize documentation from other projects under the same client due to cross-vendor access.

- Suggestions for USWDS template page:
   - a more 'functional' landing page vs. hero-orientated one
   - progression page (_example from Bri pending_)

## Participant B
- Tools currently using:
   - Front-end dev stack, USWDS, etc.

- Initial impressions:
   - It's always nice having these templates and patterns, I think other agencies have also expressed interest in sharing some of the more common problems they're solving with these components and sharing it with the community.
   - I don't think there are many people taking the [USWDS templates] too far; there has been some improvement but people are still learning about the tokens.

- Suggestions:
   - rendered HTML would be the simplest and most 'open' way to share 
   - make sure proper accessibility guidelines are met to prevent users from using bad practices
   - look into using USWDS Sandbox for compiling SASS
   - (In terms of communicating this work to others), I think [giving presentations] would be the best way to demonstrate this vs. sharing it on the USWDS Slack channel

## Participant C
- Tools currently using:
   - Sketch, USWDS, etc.

- Initial impressions:
   - I see a big gap in USWDS because there's only a few page templates. I think having more of those would be good.
   - When I was on USWDS and doing some landscape analysis, I noticed that many other design systems have a whole section on patterns and how to use multiple components to do something bigger.
   - Could this be helpful for a team with no designers and few developers? Yes! This could really support USWDS's effort to address teams that have limited resources, which is one of the items on their roadmap

- Things to think about:
   - (WIOA/HHS) Does the project value validation of a concept over the content/interaction?
      - If yes, templates may not be needed for this
   - (SSA) Does the project already have an established design concept?
      - If yes, templates could potentially help inform designs, but may not be utilized
   - (GHSC) Does the client utilize their own design framework (not USWDS)?
      - If yes, there could be encouragement to use the templates on top of their existing system
